# Generated by Django 4.1 on 2024-01-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flick_seeker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='bad_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='good_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
