# Generated by Django 4.1 on 2024-01-30 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flick_seeker', '0003_vote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritemovie',
            unique_together={('user', 'movie')},
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
