# Generated by Django 4.1 on 2024-02-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flick_seeker', '0004_alter_favoritemovie_unique_together_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='movie_thumbnails/'),
        ),
    ]
