# Generated by Django 4.1 on 2024-02-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flick_seeker', '0006_review_spoiler_review_title_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='category',
            field=models.CharField(choices=[('genre', 'ジャンル'), ('situation', 'シチュエーション')], default='genre', max_length=50),
        ),
    ]
