# Generated by Django 4.1 on 2024-02-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flick_seeker', '0008_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default-thumbnail.png', null=True, upload_to='profile_images/'),
        ),
    ]
