# Generated by Django 4.1 on 2024-03-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flick_seeker', '0010_user_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
